// The state's pointer map (docs/state.md). Every world knows where in its
// memory an address may be kept: one bit per 4 bytes. Copying a world to
// another's memory moves the addresses at those places that point into it.
//
// Variables are mapped from their types (tools/state/types.py generates their
// descriptors); memory handed out at run time (the pools) is mapped where it
// is allocated, with host_mark.
#ifndef SM64_PLATFORM_POINTERS_H
#define SM64_PLATFORM_POINTERS_H

#include <stddef.h>

// A type's places that hold addresses.
struct host_field {
    size_t offset;
    // NULL: an address; else a type holding some.
    const struct host_type *type;
    // Elements, stride apart (1 for a single one).
    size_t count, stride;
};

struct host_type {
    size_t size;
    size_t field_count;
    const struct host_field *fields;
};

// An address.
extern const struct host_type gHostTypeAddress;

// A state variable of a type holding addresses: count elements of type at
// address (in the state section).
struct host_variable {
    const void *address;
    const struct host_type *type;
    size_t count;
};

// The tables of state variables hold the variables' addresses in the section
// to know where they are, not to reach them: the build's check that nothing
// outside the state points into it (tools/state/init_pointers.py) leaves
// their section out.
#define HOST_VARIABLE_TABLE __attribute__((section("sm64_state_variables")))

// Registered at load time by each state source (its generated
// <source>.pointers.inc.c).
void host_register_variables(const struct host_variable *variables, size_t count);

#define HOST_REGISTER_VARIABLES(table)                                                                 \
    __attribute__((constructor)) static void host_register_##table(void) {                             \
        host_register_variables(table, sizeof(table) / sizeof(table[0]));                               \
    }

// The descriptor of a struct tag or typedef, for host_mark (generated by
// tools/state/types.py from the uses of HOST_TYPE_OF in the game's sources).
#define HOST_TYPE_OF(name) (&gHostType_##name)
#include "pointers/types.h"

// In the current world: size bytes at p hold no addresses.
void host_mark_raw(void *p, size_t size);
// In the current world: count elements of type at p (and nothing else there).
void host_mark(void *p, const struct host_type *type, size_t count);
// In the current world: an address is kept at p.
void host_mark_address(void *p);

// Where the current world's memory was handed out, and to whom: for finding
// memory whose addresses are not marked (sm64_run --pointers). Off unless the
// environment has SM64_NOTE_ALLOCATIONS.
void host_note_allocation(void *p, size_t size, void *caller);
// The code that allocated what is at offset in world's memory (a
// sm64_world *), or NULL: memory nothing allocated holds.
void *sm64_world_allocation_at(const void *world, size_t offset);
// Memory [start, end) of the current world was given back: its allocations
// end.
void host_note_release(const void *start, const void *end);

#endif
