#!/usr/bin/env python3
"""The pointers among the state's initial values.

  init_pointers.py OBJECT OUT_C

OBJECT is the library's object (sm64_game.o, platform/state.ld). Its
relocations in sm64_state say which initialized words hold an address; those
whose target is itself in sm64_state point into the state and have to move
with every copy of it (platform/world.c). Writes their offsets as a C table.

Fails if data outside the state holds an address in it: code that reads such
a pointer would reach the section itself, not the current world's copy.
"""
import re
import subprocess
import sys


def main():
    obj, out = sys.argv[1], sys.argv[2]
    sections = subprocess.run(["readelf", "-SW", obj], check=True, capture_output=True, text=True).stdout
    names = {int(m.group(1)): m.group(2) for m in re.finditer(r"^\s*\[\s*(\d+)\]\s+(\S+)", sections, re.M)}
    state = next(i for i, n in names.items() if n == "sm64_state")
    symbols = subprocess.run(["readelf", "-sW", obj], check=True, capture_output=True, text=True).stdout
    in_state = set()
    for line in symbols.splitlines():
        parts = line.split()
        if len(parts) == 8 and parts[6] == str(state):
            in_state.add(parts[7])
    relocations = subprocess.run(["readelf", "-rW", obj], check=True, capture_output=True, text=True).stdout
    offsets, current, outside = [], None, []
    for line in relocations.splitlines():
        if line.startswith("Relocation section"):
            current = re.search(r"'\.rela(\S+)'", line).group(1)
            continue
        parts = line.split()
        if current is None or len(parts) < 5 or not re.fullmatch(r"[0-9a-f]+", parts[0]):
            continue
        if current != "sm64_state":
            # Code reaches the state through WORLD(); data must not.
            if not current.startswith((".text", ".eh_frame", ".debug")) and (
                    parts[4] == "sm64_state" or parts[4] in in_state):
                outside.append(f"{current}+0x{parts[0]} -> {parts[4]}")
            continue
        if parts[2] != "R_X86_64_64":
            sys.exit(f"init_pointers.py: unexpected relocation {parts[2]} in sm64_state")
        target = parts[4]
        if target == "sm64_state" or target in in_state:
            offsets.append(int(parts[0], 16))
    if outside:
        sys.exit("init_pointers.py: data outside the state points into it:\n  " + "\n  ".join(outside))
    with open(out, "w") as f:
        f.write("// Generated by tools/state/init_pointers.py: the offsets in the state of\n"
                "// initial values that are addresses in the state.\n"
                "#include <stddef.h>\n#include <stdint.h>\n\n"
                f"const uint32_t gHostStatePointers[] = {{\n")
        for i in range(0, len(offsets), 8):
            f.write("    " + ", ".join(f"0x{o:x}" for o in offsets[i:i + 8]) + ",\n")
        f.write(f"}};\nconst size_t gHostStatePointerCount = {len(offsets)};\n")
    print(f"{len(offsets)} pointers in the state's initial values")


if __name__ == "__main__":
    main()
