#!/usr/bin/env python3
"""Generate the N64 stack model's frame tables.

  frames.py BUILD_DIR SYMBOLS_TSV OUT_DIR SOURCE[=COMPILED]...

BUILD_DIR is the decomp's matching build (build/jp): each SOURCE's object
there holds, in its .mdebug data, a procedure descriptor for every function,
static ones included, with the size of its stack frame. For each SOURCE this
writes OUT_DIR/n64stack_<name>.c, which includes the source (or COMPILED, a
patched copy of it) and registers its functions' frame sizes with the host
(platform/n64stack.c). It also writes OUT_DIR/n64_frames.h with the game
thread's stack pointer and the frames of functions patches refer to.
"""
import struct
import sys
from pathlib import Path

ST_PROC, ST_STATIC_PROC = 6, 14


def procedures(obj_path):
    """[(name, frame size)] of the functions in an IDO object."""
    data = Path(obj_path).read_bytes()
    shoff, = struct.unpack_from(">I", data, 0x20)
    shentsize, shnum, shstrndx = struct.unpack_from(">HHH", data, 0x2e)
    sections = [struct.unpack_from(">IIIIIIIIII", data, shoff + i * shentsize) for i in range(shnum)]
    names = sections[shstrndx]

    def section_name(header):
        start = names[4] + header[0]
        return data[start:data.index(b"\0", start)].decode()

    mdebug = next(s for s in sections if section_name(s) == ".mdebug")
    header = struct.unpack_from(">HH" + "I" * 23, data, mdebug[4])
    cb_pd, cb_sym, cb_ss, ifd_max, cb_fd = header[8], header[10], header[16], header[19], header[20]
    result = []
    for f in range(ifd_max):
        fdr = struct.unpack_from(">IIIIIIIIIIHHIIIIIII", data, cb_fd + f * 72)
        iss_base, isym_base, ipd_first, cpd = fdr[2], fdr[4], fdr[10], fdr[11]
        for p in range(cpd):
            pdr = struct.unpack_from(">IiiiiiiiihhiiI", data, cb_pd + (ipd_first + p) * 52)
            isym, frame = pdr[1], pdr[8]
            iss, _, bits = struct.unpack_from(">IiI", data, cb_sym + (isym_base + isym) * 12)
            if bits >> 26 not in (ST_PROC, ST_STATIC_PROC):
                continue
            start = cb_ss + iss_base + iss
            result.append((data[start:data.index(b"\0", start)].decode(), frame))
    return result


def main():
    if len(sys.argv) < 5:
        sys.exit(__doc__)
    build, symbols, out = Path(sys.argv[1]), Path(sys.argv[2]), Path(sys.argv[3])
    out.mkdir(parents=True, exist_ok=True)
    frames = {}
    for spec in sys.argv[4:]:
        source, _, compiled = spec.partition("=")
        compiled = compiled or source
        # src/game/mario.c -> build/jp/src/game/mario.o
        relative = source.split("/src/", 1)[1]
        procs = procedures(build / "src" / relative.replace(".c", ".o"))
        name = Path(source).stem
        lines = [
            "// Generated by tools/n64stack/frames.py. Do not edit.",
            f'#include "{compiled}"',
            '#include "n64stack.h"',
            "",
            f"static const struct n64_frame sN64Frames_{name}[] = {{",
        ]
        for proc, frame in procs:
            lines.append(f"    {{ (const void *) {proc}, {frame} }},")
            frames[proc] = frame
        lines += [
            "};",
            "",
            f"N64STACK_REGISTER({name}, sN64Frames_{name})",
            "",
        ]
        (out / f"n64stack_{name}.c").write_text("\n".join(lines))

    # The game thread's stack: osCreateThread starts it 16 bytes below the top
    # given by create_thread (gThread5Stack + 0x2000).
    stack = None
    for line in symbols.read_text().splitlines():
        parts = line.split("\t")
        if parts[0] == "gThread5Stack":
            stack = int(parts[1], 16) + int(parts[2])
    game_init = dict(procedures(build / "src" / "game" / "game_init.o"))
    camera = dict(procedures(build / "src" / "game" / "camera.o"))
    (out / "n64_frames.h").write_text(
        "// Generated by tools/n64stack/frames.py. Do not edit.\n#pragma once\n"
        f"// The N64 stack pointer inside thread5_game_loop.\n"
        f"#define N64_GAME_LOOP_SP 0x{stack - 16 - game_init['thread5_game_loop']:08x}u\n"
        f"#define N64_FRAME_set_camera_mode {camera['set_camera_mode']}\n")


if __name__ == "__main__":
    main()
