#!/usr/bin/env python3
"""The N64 stack model's frames.

  frames.py export BUILD_DIR TARGET SYMBOLS_TSV OUT_TSV
  frames.py apply GAME_DIR TABLE_TSV...
  frames.py header OUT_H TABLE_TSV [OTHER_TABLE_TSV...]

The model has to be right wherever the original leaks a stack address or
leftover stack contents (docs/avoid_ub.md): inside set_camera_mode, where
find_floor_from_list leaves a vertex on the stack, and where
bhv_jrb_sliding_box_loop reads it back. So every function from which the N64
can call one of those, and they themselves, move the modelled stack pointer
by their N64 frame; nothing else does.

export reads which functions those are, and their frame sizes, from a matching
build of n64decomp/sm64 (BUILD_DIR/TARGET, e.g. build/jp, sm64.jp; see
callgraph.py), with the game thread's stack pointer from SYMBOLS_TSV, and
writes them to OUT_TSV (tools/n64stack/<version>.tsv, committed).

apply opens every function the tables list, in the game's sources under
GAME_DIR, with N64_STACK_FRAME(name); (platform/n64stack.h). Run it with every
version's table after export; like tools/state/rewrite.py it edits the
committed sources and changes nothing when they are up to date.

header runs at configure time: it writes OUT_H with the game thread's stack
pointer and each function's frame in the version being built (the first
table), 0 for those only another version moves by.
"""
import re
import sys
from pathlib import Path

TARGETS = ("set_camera_mode", "find_floor_from_list", "bhv_jrb_sliding_box_loop")

# Goddard's function pointers only lead to goddard: its indirect calls do not
# reach the game.
GODDARD = "/src/goddard/"


def export(build, target, symbols, out):
    sys.path.insert(0, str(Path(__file__).parent))
    import callgraph

    funcs, graph = callgraph.call_graph(
        build, target, lambda caller, callee: GODDARD not in caller.object or GODDARD in callee.object)
    targets = [f for f in funcs if f.name in TARGETS]
    hooked = callgraph.ancestors(graph, targets) | set(targets)

    # The game thread's stack: osCreateThread starts it 16 bytes below the top
    # given by create_thread (gThread5Stack + 0x2000).
    stack = None
    for line in Path(symbols).read_text().splitlines():
        parts = line.split("\t")
        if parts[0] == "gThread5Stack":
            stack = int(parts[1], 16) + int(parts[2])
    loop = next(f for f in funcs if f.name == "thread5_game_loop")
    prefix = f"{Path(build).relative_to(Path(build).parent.parent)}/"
    lines = [
        f"# Generated by tools/n64stack/frames.py export from {prefix}{target}.elf. Functions on the",
        f"# N64's call paths to {', '.join(TARGETS)}, with their stack frame sizes.",
        f"game_loop_sp\t0x{stack - 16 - loop.frame:08x}",
    ]
    for f in sorted(hooked, key=lambda f: (f.object, f.address)):
        source = f.object[len(prefix):-2] + ".c"
        lines.append(f"{source}\t{f.name}\t{f.frame}")
    Path(out).write_text("\n".join(lines) + "\n")


def read_table(table):
    """(game_loop_sp, [(source, function, frame)]) of a version's table."""
    game_loop_sp, functions = None, []
    for line in Path(table).read_text().splitlines():
        if line.startswith("#"):
            continue
        fields = line.split("\t")
        if fields[0] == "game_loop_sp":
            game_loop_sp = fields[1]
        else:
            functions.append((fields[0], fields[1], int(fields[2])))
    return game_loop_sp, functions


def included_sources(path, seen=None):
    """A C file and the .c files it includes, recursively."""
    seen = seen if seen is not None else []
    path = Path(path)
    if path in seen or not path.exists():
        return seen
    seen.append(path)
    for include in re.findall(r'^#include\s+"([^"]+\.c)"', path.read_text(errors="replace"), re.M):
        included_sources(path.parent / include, seen)
    return seen


def definitions(text, name):
    """Offsets just past the opening brace of each definition of name."""
    # (Preprocessor lines may come before the brace: a prototype per #ifdef.)
    pattern = r"^[A-Za-z_][\w \t\*\(\)]*?\b" + re.escape(name) + r"\s*\([^;{}]*\)\s*(?:#\w+[^\n]*\n\s*)*\{"
    return [m.end() for m in re.finditer(pattern, text, re.M)]


def apply(game, tables):
    functions = {}
    for table in tables:
        for source, name, _ in read_table(table)[1]:
            if not source.startswith("lib/"):
                functions.setdefault(source, set()).add(name)
    failed = False
    for source, names in sorted(functions.items()):
        files = included_sources(Path(game) / source)
        if not files:
            print(f"frames.py: {source} not found", file=sys.stderr)
            failed = True
            continue
        texts = {f: f.read_text() for f in files}
        for name in sorted(names):
            found = False
            for f in files:
                text = texts[f]
                for end in reversed(definitions(text, name)):
                    found = True
                    statement = f"\n    N64_STACK_FRAME({name});"
                    if not text.startswith(statement, end):
                        text = text[:end] + statement + text[end:]
                texts[f] = text
            if not found:
                print(f"frames.py: no definition of {name} in {source}", file=sys.stderr)
                failed = True
        for f, text in texts.items():
            write_if_changed(f, text)
    if failed:
        sys.exit(1)


def write_if_changed(path, text):
    if not path.exists() or path.read_text() != text:
        path.write_text(text)


def header(out, table, others):
    game_loop_sp, functions = read_table(table)
    frames = {name: frame for _, name, frame in functions}
    for other in others:
        for _, name, _ in read_table(other)[1]:
            frames.setdefault(name, 0)
    lines = [
        "// Generated by tools/n64stack/frames.py. Do not edit.",
        "#pragma once",
        "// The N64 stack pointer inside thread5_game_loop.",
        f"#define N64_GAME_LOOP_SP {game_loop_sp}u",
        "// The N64 frame of each function on the paths to the model's targets.",
    ]
    lines += [f"#define N64_FRAME_{name} {frame}" for name, frame in sorted(frames.items())]
    out = Path(out)
    out.parent.mkdir(parents=True, exist_ok=True)
    write_if_changed(out, "\n".join(lines) + "\n")


def main():
    if len(sys.argv) >= 6 and sys.argv[1] == "export":
        export(*sys.argv[2:6])
    elif len(sys.argv) >= 4 and sys.argv[1] == "apply":
        apply(sys.argv[2], sys.argv[3:])
    elif len(sys.argv) >= 4 and sys.argv[1] == "header":
        header(sys.argv[2], sys.argv[3], sys.argv[4:])
    else:
        sys.exit(__doc__)


if __name__ == "__main__":
    main()
