#!/usr/bin/env python3
"""Rebuild the game's sound data in the host's layout.

  native_sound.py DECOMP_DIR VERSION OUT_DIR

The decomp's N64 build lays the instrument banks and the sequence table out
big endian with 32-bit pointers; the audio code reads them in the host's
layout. The decomp's own assemble_sound.py writes that layout from the samples
and sequences the N64 build already produced. Writes OUT_DIR/sound_data.c,
compiled in place of sound/sound_data.c.
"""
import subprocess
import sys
from pathlib import Path

DEFINES = {"jp": ["-DVERSION_JP=1", "-DF3D_OLD=1", "-D_FINALROM=1"]}


def to_inc_c(binary, inc):
    data = binary.read_bytes()
    inc.write_text(",".join(f"0x{b:02X}" for b in data) + ",\n")


def main():
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    decomp, version, out = Path(sys.argv[1]).resolve(), sys.argv[2], Path(sys.argv[3]).resolve()
    gen = decomp / "build" / version / "sound"
    out.mkdir(parents=True, exist_ok=True)
    layout = ["--endian", "little", "--bitwidth", "64"]
    tool = str(decomp / "tools" / "assemble_sound.py")
    subprocess.run([sys.executable, tool, str(gen / "samples") + "/", "sound/sound_banks/",
                    str(out / "sound_data.ctl"), str(out / "ctl_header"), str(out / "sound_data.tbl"),
                    str(out / "tbl_header")] + DEFINES[version] + layout, cwd=decomp, check=True)
    # As the Makefile: .m64 files in sound/sequences and its version folder,
    # plus the ones assembled from .s files there.
    sequences = sorted(str(p) for folder in [decomp / "sound" / "sequences", decomp / "sound" / "sequences" / version,
                                             gen / "sequences", gen / "sequences" / version]
                       for p in folder.glob("*.m64"))
    subprocess.run([sys.executable, tool, "--sequences", str(out / "sequences.bin"), str(out / "sequences_header"),
                    str(out / "bank_sets"), "sound/sound_banks/", "sound/sequences.json"] + sequences
                   + DEFINES[version] + layout, cwd=decomp, check=True)
    for name in ["sound_data.ctl", "sound_data.tbl", "sequences.bin", "bank_sets"]:
        to_inc_c(out / name, out / f"{name}.inc.c")
    # sound/sound_data.c, including these instead of the N64 layout.
    (out / "sound_data.c").write_text(
        "// Generated by tools/native_sound.py: sound/sound_data.c with the host's layout.\n"
        "unsigned char gSoundDataADSR[] = {\n#include \"sound_data.ctl.inc.c\"\n};\n"
        "unsigned char gSoundDataRaw[] = {\n#include \"sound_data.tbl.inc.c\"\n};\n"
        "unsigned char gMusicData[] = {\n#include \"sequences.bin.inc.c\"\n};\n"
        "unsigned char gBankSetsData[] = {\n#include \"bank_sets.inc.c\"\n};\n")


if __name__ == "__main__":
    main()
