#!/usr/bin/env python3
"""Copy the game's code from an n64decomp/sm64 checkout into game/.

  vendor.py DECOMP_DIR PATCH_DIR OUT_DIR DEPFILE_DIR...

A one-time (and reviewable) import: the library owns its copy of the game from
then on, and the decomp stays a reference. Copied are the decomp's own files
(tracked in its git repository, never anything extracted from a ROM) that the
JP and US builds read, found from the compiler's dependency files in each
DEPFILE_DIR (a build of this library before the import), with every patch in
PATCH_DIR applied.

Files the decomp's build generates from its own sources (text, level headers,
Mario's animation data) go to OUT_DIR/gen/<version>/. What it extracts from the
ROM does not come along: OUT_DIR/rom_assets/<version>.tsv lists it (textures,
skyboxes, demo inputs), for the build to stub and the game to load from the
user's ROM.
"""
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

VERSIONS = ["jp", "us"]


def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


def tiled_stub(generated, where, keep=""):
    """A generated file of texture arrays cut from one ROM image (a skybox's
    tiles, the ending's cake), as the same arrays, each a stand-in tagged with
    where its pixels are (tools/rom_stubs.py), and the file's other
    declarations (a skybox's list of tiles) as they are."""
    sys.path.insert(0, str(Path(__file__).parent))
    from rom_stubs import stub
    text = generated.read_text()
    arrays = re.finditer(r"^((?:ALIGNED8 )?(?:static )?const Texture (\w+)\[\]) = \{\n(.*?)^\};\n", text, re.M | re.S)
    lines = ["// Generated by tools/vendor.py: the ROM's textures, as stand-ins tagged with",
             "// where their pixels are (tools/rom_stubs.py).", '#include "types.h"', ""]
    offset = where[1]
    for array in arrays:
        size = array.group(3).count("0x")
        lines.append(f"{array.group(1)} = {{ {stub([where[0], offset], size).strip()} }};")
        offset += size
    if keep:
        lines += [""] + re.findall(r"^const Texture \*const \w+%s\[\] = \{.*?\};$" % keep, text, re.M | re.S)
    return "\n".join(lines) + "\n"


def main():
    decomp, patches, out = Path(sys.argv[1]).resolve(), Path(sys.argv[2]), Path(sys.argv[3])
    tracked = set(subprocess.run(["git", "ls-files"], cwd=decomp, check=True, capture_output=True,
                                 text=True).stdout.split("\n"))
    deps = set()
    for build in sys.argv[4:]:
        for depfile in Path(build).rglob("*.d"):
            text = depfile.read_text().replace("\\\n", " ")
            for line in text.splitlines():
                if ":" in line:
                    deps.update(os.path.normpath(p) for p in line.split(":", 1)[1].split())

    repo, generated = set(), set()
    for dep in deps:
        # Patched copies (build/overlay/...) stand for the decomp's file.
        match = re.search(r"/overlay/(.*)$", dep)
        if match and match.group(1) in tracked:
            repo.add(match.group(1))
            continue
        if not dep.startswith(str(decomp) + "/"):
            continue
        relative = dep[len(str(decomp)) + 1:]
        if relative.startswith("build/"):
            generated.add(relative)
        elif relative in tracked:
            repo.add(relative)
        else:
            sys.exit(f"vendor.py: {relative} is neither tracked nor generated")
    # Every header, for the tools that read the game's types.
    repo.update(f for f in tracked if f.startswith("include/"))
    # The sound banks' and sequences' sources, for building sound later.
    repo.update(f for f in tracked if f.startswith("sound/"))

    game = out / "game"
    if game.exists():
        shutil.rmtree(game)
    for relative in sorted(repo):
        (game / relative).parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(decomp / relative, game / relative)
    for patch in sorted(Path(patches).glob("*.patch")):
        subprocess.run(["patch", "-s", "-p1", "-d", str(game), "-i", str(patch.resolve())], check=True)

    # Generated from the decomp's sources: copied. From the ROM: listed.
    assets = json.loads((decomp / "assets.json").read_text())
    rom = {v: [] for v in VERSIONS}
    for relative in sorted(generated):
        _, version, rest = relative.split("/", 2)
        if rest.endswith(".inc.c") and re.search(r"\.(rgba16|rgba32|ia16|ia8|ia4|ia1|i8|i4|ci8|ci4)\.inc\.c$", rest):
            png = rest[:-len(".inc.c")] + ".png"
            info = assets.get(png)
            if info is None:
                sys.exit(f"vendor.py: no ROM location for {png}")
            rom[version].append(("texture", rest, info[-2] if len(info) > 3 else info[0], info[-1].get(version)))
        elif re.match(r"bin/\w+_skybox\.c$", rest):
            # Tiles of the sky image: kept with their names, without pixels.
            name = re.match(r"bin/(\w+)_skybox\.c$", rest).group(1)
            info = assets[f"textures/skyboxes/{name}.png"]
            rom[version].append(("skybox", rest, info[0], info[-1][version]))
            write(game / "gen" / version / rest, tiled_stub(decomp / relative, info[-1][version], "_ptrlist"))
        elif rest == "levels/ending/cake.inc.c":
            info = assets["levels/ending/cake.png"]
            rom[version].append(("cake", rest, info[0], info[-1][version]))
            write(game / "gen" / version / rest, tiled_stub(decomp / relative, info[-1][version]))
        elif rest == "assets/demo_data.c":
            for name in sorted(k for k in assets if k.startswith("assets/demos/")):
                if version in assets[name][-1]:
                    rom[version].append(("demo", name, assets[name][0], assets[name][-1][version]))
            # The layout with the inputs zeroed: sm64_load_rom copies them in.
            text = re.sub(r"^\{0x[0-9a-fx,]*\},?$", "{0},", (decomp / relative).read_text(), flags=re.M)
            text += "\n#include <string.h>\n\n// Library: the demo inputs, from the ROM (platform/host.c).\n"
            text += "void host_load_demo_inputs(const unsigned char *rom) {\n"
            for kind, name, size, where in rom[version]:
                if kind == "demo":
                    field = Path(name).stem
                    text += f"    memcpy(gDemoInputs.{field}, rom + 0x{where[0]:x}, sizeof(gDemoInputs.{field}));\n"
            text += "}\n"
            write(game / "gen" / version / rest, text)
        else:
            (game / "gen" / version / rest).parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(decomp / relative, game / "gen" / version / rest)
    (out / "game" / "rom_assets").mkdir(exist_ok=True)
    for version in VERSIONS:
        with open(out / "game" / "rom_assets" / f"{version}.tsv", "w") as f:
            f.write("# kind\tpath\tsize\tROM location (MIO0 block offset and offset in it, or file offset)\n")
            for kind, path, size, where in rom[version]:
                f.write(f"{kind}\t{path}\t{size}\t{json.dumps(where)}\n")
    print(f"{len(repo)} files, {sum(len(r) for r in rom.values())} ROM assets listed")


if __name__ == "__main__":
    main()
